src/EquipmentReservation/Models/ReservationViewModel.cs
using EquipmentReservation.Application.Accounts.Data;
using EquipmentReservation.Application.Equipments.Data;
using EquipmentReservation.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EquipmentReservation.Models
{
    public class ReservationViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "利用者は必須入力です。")]
        public string SelectedAccountId { get; set; }
        public IEnumerable<AccountData> AccountList { get; set; }

        [Required(ErrorMessage = "備品は必須入力です。")]
        public string SelectedEquipmentId { get; set; }
        public IEnumerable<EquipmentData> EquipmentList { get; set; }

        [Required(ErrorMessage = "利用開始日付は必須入力です。")]
        public DateTime? StartDate { get; set; }
        [Required(ErrorMessage = "利用開始時間は必須入力です。")]
        public DateTime? StartTime { get; set; }

        [Required(ErrorMessage = "利用終了日付は必須入力です。")]
        public DateTime? EndDate { get; set; }
        [Required(ErrorMessage = "利用終了時間は必須入力です。")]
        [StartEndDateTimeValidation(
            StartDatePropertyName = nameof(StartDate), 
            StartTimePropertyName = nameof(StartTime), 
            EndDatePropertyName = nameof(EndDate), 
            ErrorMessage = "利用終了日時は利用開始日時よりも後にしてください。")]
        public DateTime? EndTime { get; set; }

        [StringLength(64, ErrorMessage = "利用目的は {1} 文字以内で入力してください。")]
        public string PurposeOfUse { get; set; }

        public bool IsReadOnly { get; set; }

        public DateTime? GetStartDateTime()
        {
            return CombineDateTime(StartDate, StartTime);
        }
       
        public DateTime? GetEndDateTime()
        {
            return CombineDateTime(EndDate, EndTime);
        }

        private DateTime? CombineDateTime(DateTime? date, DateTime? time)
        {
            if (!date.HasValue || !time.HasValue) return null;
            return date.Value.Date + time.Value.TimeOfDay;
        }
    }
}

src/EquipmentReservation/Controllers/ReservationController.cs
using EquipmentReservation.Application.Accounts;
using EquipmentReservation.Application.Equipments;
using EquipmentReservation.Application.Reservations;
using EquipmentReservation.Application.Reservations.Commands;
using EquipmentReservation.Application.Reservations.Exceptions;
using EquipmentReservation.Application.Reservations.Queries;
using EquipmentReservation.Models;
using Microsoft.AspNetCore.Mvc;

namespace EquipmentReservation.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationAppService _reservationAppService;
        private readonly IReservationQueryService _reservationQueryService;
        private readonly IAccountQueryService _accountQueryService;
        private readonly IEquipmentQueryService _equipmentQueryService;

        public ReservationController(
            IReservationAppService reservationAppService, 
            IReservationQueryService reservationQueryService,
            IAccountQueryService accountQueryService,
            IEquipmentQueryService equipmentQueryService)
        {
            _reservationAppService = reservationAppService;
            _reservationQueryService = reservationQueryService;
            _accountQueryService = accountQueryService;
            _equipmentQueryService = equipmentQueryService;
        }

        public IActionResult Index()
        {
            var reservations = _reservationQueryService.GetAllReservationListData().ReservationListDataList;
            return View(reservations);
        }

        public IActionResult NewReservation()
        {
            var model = new ReservationViewModel();
            model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
            model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
            return View(model);
        }

        [HttpPost]
        public IActionResult NewReservation(ReservationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
                model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
                ModelState.AddModelError(string.Empty, "入力内容が不正です。");
                return View(model);
            }

            var request = new RegisterReservationRequest()
            {
                AccountId = model.SelectedAccountId,
                EquipmentId = model.SelectedEquipmentId,
                StartDateTime = model.GetStartDateTime().Value,
                EndDateTime = model.GetEndDateTime().Value,
                PurposeOfUse = model.PurposeOfUse
            };

            try
            {
                _reservationAppService.RegisterReservation(request);
            }
            catch (ReservationDupulicationException)
            {
                model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
                model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
                ModelState.AddModelError(string.Empty, "予約が重複しています。");
                return View(model);
            }

            return RedirectToAction("Index");
        }

        public IActionResult EditReservation(string reservationId)
        {
            var model = CreateReservationViewModel(reservationId);
            return View(model);
        }

        [HttpPost]
        public IActionResult EditReservation(ReservationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
                model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
                ModelState.AddModelError(string.Empty, "入力内容が不正です。");
                return View(model);
            }

            var request = new ChangeReservationInfoRequest()
            {
                ReservationId = model.Id,
                AccountId = model.SelectedAccountId,
                EquipmentId = model.SelectedEquipmentId,
                StartDateTime = model.GetStartDateTime().Value,
                EndDateTime = model.GetEndDateTime().Value,
                PurposeOfUse = model.PurposeOfUse
            };

            try
            {
                _reservationAppService.ChangeReservationInfo(request);
            }
            catch (ReservationDupulicationException)
            {
                model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
                model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
                ModelState.AddModelError(string.Empty, "予約が重複しています。");
                return View(model);
            }

            return RedirectToAction("Index");
        }

        public IActionResult CancelReservation(string reservationId)
        {
            var model = CreateReservationViewModel(reservationId);
            return View(model);
        }

        [HttpPost]
        public IActionResult CancelReservation(ReservationViewModel model)
        {
            var request = new CancelReservationRequest()
            {
                ReservationId = model.Id
            };

            _reservationAppService.CancelReservation(request);

            return RedirectToAction("Index");
        }

        private ReservationViewModel CreateReservationViewModel(string reservationId)
        {
            var request = new GetReservationDataRequest()
            {
                ReservationId = reservationId
            };
            var response = _reservationQueryService.GetReservationData(request);

            var model = new ReservationViewModel();
            model.AccountList = _accountQueryService.GetAllAccountData().AccountDataList;
            model.EquipmentList = _equipmentQueryService.GetAllEquipmentData().EquipmentDataList;
            model.Id = response.ReservationData.Id;
            model.SelectedAccountId = response.ReservationData.AccountId;
            model.SelectedEquipmentId = response.ReservationData.EquipmentId;
            model.StartDate = response.ReservationData.StartDateTime;
            model.StartTime = response.ReservationData.StartDateTime;
            model.EndDate = response.ReservationData.EndDateTime;
            model.EndTime = response.ReservationData.EndDateTime;
            model.PurposeOfUse = response.ReservationData.PurposeOfUse;

            return model;
        }
    }
}

src/EquipmentReservation/Views/Reservation/CancelReservation.cshtml
@model EquipmentReservation.Models.ReservationViewModel
@{
    ViewBag.Title = "予約キャンセル";
}

<h2>予約キャンセル</h2>

@using (Html.BeginForm("CancelReservation", "Reservation"))
{
    <label>キャンセルしますか？</label>

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <label>利用者</label>
        @Html.DropDownListFor(model => model.SelectedAccountId, new SelectList(Model.AccountList, "Id", "AccountName", 1), "-- 選択してください --", new { @class = "form-control", @disabled = "disabled" })
    </div>
    <div class="form-group">
        <label>備品</label>
        @Html.DropDownListFor(model => model.SelectedEquipmentId, new SelectList(Model.EquipmentList, "Id", "EquipmentName", 1), "-- 選択してください --", new { @class = "form-control", @disabled = "disabled" })
    </div>
    <div class="form-group">
        <label>利用開始日時</label>
        <input asp-for="StartDate" class="form-control" type="date" disabled="disabled" />
        <input asp-for="StartTime" class="form-control" type="time" disabled="disabled" />
    </div>
    <div class="form-group">
        <label>利用終了日時</label>
        <input asp-for="EndDate" class="form-control" type="date" disabled="disabled" />
        <input asp-for="EndTime" class="form-control" type="time" disabled="disabled" />
    </div>
    <div class="form-group">
        <label>利用目的</label>
        <input asp-for="PurposeOfUse" class="form-control" placeholder="利用目的" disabled="disabled" />
    </div>

    <input type="submit" class="btn btn-primary" value="キャンセル" />
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/EquipmentReservation/Views/Reservation/EditReservation.cshtml
@model EquipmentReservation.Models.ReservationViewModel
@{
    ViewBag.Title = "予約変更";
}

<h2>予約変更</h2>

@using (Html.BeginForm("EditReservation", "Reservation"))
{
    @Html.Partial("_ReservationPartial", Model)
    <input type="submit" class="btn btn-primary" value="変更" />
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

src/EquipmentReservation/Views/Reservation/Index.cshtml
@model IEnumerable<EquipmentReservation.Application.Reservations.Data.ReservationListData>

@{
    ViewBag.Title = "予約一覧";
}

<h2>予約一覧</h2>
<p>
    @Html.ActionLink(
        "新規予約",
        "NewReservation",
        "Reservation",
        new { },
        new { @class = "btn btn-default" }
        )
</p>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>利用者</th>
                <th>備品</th>
                <th>利用開始日時</th>
                <th>利用終了日時</th>
                <th>利用目的</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reservation in Model)
            {
            <tr>
                <td>@reservation.AccountName</td>
                <td>@reservation.EquipmentName</td>
                <td>@reservation.StartDateTime</td>
                <td>@reservation.EndDateTime</td>
                <td>@reservation.PurposeOfUse</td>
                <td>@Html.ActionLink("変更", "EditReservation", "Reservation", new { reservationId = reservation.Id }, new { @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("キャンセル", "CancelReservation", "Reservation", new { reservationId = reservation.Id }, new { @class = "btn btn-default" })</td>
            </tr>
            }
        </tbody>
    </table>
</div>

src/EquipmentReservation/Views/Reservation/NewReservation.cshtml
@model EquipmentReservation.Models.ReservationViewModel
@{
    ViewBag.Title = "新規予約";
}

<h2>新規予約</h2>

@using (Html.BeginForm("NewReservation", "Reservation"))
{
    @Html.Partial("_ReservationPartial", Model)
    <input type="submit" class="btn btn-primary" value="予約" />
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

src/EquipmentReservation/Views/Reservation/_ReservationPartial.cshtml
@model EquipmentReservation.Models.ReservationViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

@Html.HiddenFor(model => model.Id)

<div class="form-group">
    <label>利用者</label>
    @Html.DropDownListFor(model => model.SelectedAccountId, new SelectList(Model.AccountList, "Id", "AccountName", 1), "-- 選択してください --", new { @class = "form-control" })
    <span asp-validation-for="SelectedAccountId" class="text-danger"></span>
</div>
<div class="form-group">
    <label>備品</label>
    @Html.DropDownListFor(model => model.SelectedEquipmentId, new SelectList(Model.EquipmentList, "Id", "EquipmentName", 1), "-- 選択してください --", new { @class = "form-control" })
    <span asp-validation-for="SelectedEquipmentId" class="text-danger"></span>
</div>
<div class="form-group">
    <label>利用開始日時</label>
    <input asp-for="StartDate" class="form-control" type="date" />
    <span asp-validation-for="StartDate" class="text-danger"></span>
    <input asp-for="StartTime" class="form-control" type="time" />
    <span asp-validation-for="StartTime" class="text-danger"></span>
</div>
<div class="form-group">
    <label>利用終了日時</label>
    <input asp-for="EndDate" class="form-control" type="date" />
    <span asp-validation-for="EndDate" class="text-danger"></span>
    <input asp-for="EndTime" class="form-control" type="time" />
    <span asp-validation-for="EndTime" class="text-danger"></span>
</div>
<div class="form-group">
    <label>利用目的</label>
    <input asp-for="PurposeOfUse" class="form-control" placeholder="利用目的" />
    <span asp-validation-for="PurposeOfUse" class="text-danger"></span>
</div>